### ISSUE TITLE
with this script I can listen my text from terminal?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jpadilla/ivona-go#4]
`go run my.go` return me

```
2016/01/20 15:51:52 5844
2016/01/20 15:51:52 audio/mpeg
2016/01/20 15:51:52 4f0894f2-4ad3-4ca6-8872-daf7a53eab70
```

where is audio?..

**Comment by jpadilla** [comment]
You'd have to write [`Audio`](https://godoc.org/github.com/jpadilla/ivona-go#SpeechResponse) to a file.

**Comment by vitaly-zdanevich** [comment]
Can you please provide code for writing audio to file?..

**Comment by jpadilla** [comment]
https://gobyexample.com/writing-files

**Comment by vitaly-zdanevich** [comment]
Thank you!
`ioutil.WriteFile("/home/vitaly/Desktop/audio.mp3", r.Audio, 0644)`
